# Zensical Configuration
# Documentation: https://zensical.org/docs/

[project]
site_name = "Tech Documentation"
site_description = "Comprehensive guides for self-hosting, infrastructure, automation, and monitoring."
site_author = "Sven van Ginkel"
repo_url = "https://github.com/svenvg93/docs"
repo_name = "svenvg93/docs"
repo = "fontawesome/brands/github"
# site_url = "https://your-domain.com/"
extra_css = ["stylesheets/extra.css"]

copyright = "Copyright &copy; 2024-2026 Sven van Ginkel"

nav = [
  {"Home" = "index.md"},
  {"Observability" = [
    {"Tools" = [
      "observability/tools/install-alloy.md",
      "observability/tools/install-grafana.md",
      "observability/tools/install-loki.md",
      "observability/tools/install-prometheus.md",
    ]},
    {"Monitoring" = [
      "observability/monitoring/host-container-monitoring.md",
      "observability/monitoring/docker-logs-loki.md",
      "observability/monitoring/system-logs-loki.md",
      "observability/monitoring/tailscale-client-metrics.md",
    ]},
  ]},
  {"Networking" = [
    {"Routers" = [
      {"Ubiquiti" = [
        "networking/routers/ubiquiti/unifi-controller-via-traefik.md",
        "networking/routers/ubiquiti/unifi-syslog-loki.md",
      ]},
      {"Mikrotik" = [
        "networking/routers/mikrotik/install-setup.md",
   #     "networking/routers/mikrotik/port-forwarding.md",
   #     "networking/routers/mikrotik/wireguard.md",
   #     "networking/routers/mikrotik/setup-monitoring.md",
      ]},
      {"GL.iNet" = [
        "networking/routers/gl-inet/travel-router-setup.md",
   #     "networking/routers/gl-inet/setup-monitoring.md",
      ]},
      {"VyOS" = [
        "networking/routers/vyos/install-setup.md",
        "networking/routers/vyos/setup-monitoring.md"
      ]},
    ]},
    {"Reverse Proxy" = [
      {"Traefik" = [
        "networking/reverse-proxy/traefik/install-setup.md",
        "networking/reverse-proxy/traefik/setup-monitoring.md",
        "networking/reverse-proxy/traefik/wildcard-ssl-certificates.md",
      ]},
    ]},
    {"VPN & Tunnels" = [
      "networking/cloudflare-tunnels.md",
    ]},
    {"Other" = [
      "networking/other/remote-packet-capture.md",
    ]},
  ]},
  {"Automation" = [
    {"Ansible" = [
      "automation/ansible/install-setup.md",
      "automation/ansible/playbooks-roles-handlers.md",
      "automation/ansible/secrets-vault.md",
    ]},
    {"GitHub Actions" = [
      "automation/cicd/dependabot-docker-compose.md",
      "automation/cicd/cloudflare-workers-github-actions.md",
      "automation/cicd/cloudflare-pages-webhook-builds.md",
    ]}
  ]}
]

# Theme Configuration
[project.theme]
language = "en"

features = [
  "announce.dismiss",
  "content.action.edit",
  "content.action.view",
  "content.code.annotate",
  "content.code.copy",
  "content.footnote.tooltips",
  "content.tabs.link",
  "content.tooltips",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.path",
  "navigation.sections",
#  "navigation.tabs",
#  "navigation.tabs.sticky",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  "toc.follow"
]

# Color Schemes
[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

# Uncomment to customize fonts
# [project.theme.font]
# text = "Inter"
# code = "Jetbrains Mono"

# Uncomment to add custom icons
# [project.theme.icon]
# logo = "lucide/smile"

# Uncomment to add social links
# [[project.extra.social]]
# icon = "fontawesome/brands/github"
# link = "https://github.com/svenvg93"
